.set @feat.00, 1

.intel_syntax
.global _USER_SHARED_DATA32, _USER_SHARED_DATA64, _USER_SHARED_DATA

_USER_SHARED_DATA = 0x7FFE0000
_USER_SHARED_DATA32 = _USER_SHARED_DATA
_USER_SHARED_DATA64 = _USER_SHARED_DATA